---
title: "eda"
author: "Wurongyan Zhang"
date: "11/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
master <- read.csv("~/Desktop/master 2.csv")
library(tidyverse)
```


```{r}
maindata = master %>% 
  janitor::clean_names() %>% 
  mutate(age=str_remove(age,"years")) %>% 
  mutate(gdp_for_year = as.numeric(gsub(",","",gdp_for_year))) %>% 
  mutate(age_group=as.factor(age))

summary(maindata)
summary(as.factor(maindata$age))

```

```{r}
try_cor=maindata %>% 
  select(-4)
plot(suicides_100k_pop~., data=try_cor)
```
comments: generation has no correlation and similar with age

# correlation matrix
```{r}
library(corrplot)
corr_data = maindata %>% 
  select(-c(1,3,4,8,9,12,13)) 


corr= cor(corr_data)
corrplot(corr, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
```

```{r}
library(leaps) 
BSS <- regsubsets(suicides_100k_pop~.,data=maindata, method="forward")
```

# transformed gdp_for_year
```{r}
plot(suicides_100k_pop~log(gdp_for_year), data=maindata)
```

# building model
```{r}
country =maindata %>% 
  filter(country =="United States") 
  
model1=lm(suicides_100k_pop~log(gdp_for_year)+year+sex+age_group+gdp_for_year+gdp_per_capita, data = country)

plot(model1)
model2=lm(suicides_100k_pop~log(gdp_for_year)+country+year+sex+age_group+gdp_for_year+gdp_per_capita, data = maindata)

plot(model)
summary(model)

# Load the library 
library(splines) 
# Fit the spline model with specified knots f
fitSpline <-lm(suicides_100k_pop~log(gdp_for_year)+country+year+sex+age_group+gdp_for_year+gdp_per_capita, data = maindata)
  lm(pop ~ bs(age, knots=c(25, 50, 75)),data=co)
```









